"""Add cascade delete to posts.author_id

Revision ID: 678f4019bc1c
Revises: 94fb2db65ddb
Create Date: 2025-04-29 21:41:31.712405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678f4019bc1c'
down_revision = '94fb2db65ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('posts_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('posts_ibfk_1', 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###
